name: m4d_components
description: Material Design 4 Dart - Basic components
version: 0.1.3
author: Mike Mitterer <office@mikemitterer.at>
homepage: http://www.material-design-lite.pub

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  validate: ^1.0.0

  logging: '>=0.11.3 <1.0.0'
  console_log_handler: ^1.0.0

  path: ^1.4.0

  m4d_core: '>=0.1.0 <1.0.0'
    # path: /Volumes/Daten/DevLocal/DevDart/m4d/m4d_core
    
dev_dependencies:
  test: any

  build_runner: any
  build_test: any
  build_web_compilers: any

